### ISSUE TITLE
Publishing to F-Droid

### ISSUE THREAD

**Issue by ljubitje** [LouisHDev/planka_app#2]
Hi.
I like Planka and I like to see a mobile app for it.
I'd like to be able to download this app via the F-Droid.
If you're okay with that, I can do the work, becuase I want to learn how to do it.
Kind regards, Klemen

**Comment by LouisHDev** [comment]
Sure :)

**Comment by ljubitje** [comment]
I am checking the requirements for inclusion in F-Droid as per [their docs](https://f-droid.org/en/docs/Inclusion_Policy/).

License is compatible.
There are no proprietary dependencies.
So far so good.

**Comment by ljubitje** [comment]
The Android ID of the app is already unique. That's the requirement.
However, it is a bit generic and better naming conventions are desired.

I see you have it marked in your code at [build.gradle](https://github.com/LouisHDev/planka_app/blob/main/android/app/build.gradle) as TODO.
Could you update it please?

From F-Droid:

> The software should use its own unique Android “[Application ID](https://developer.android.com/studio/build/configure-app-module)” based on a domain name under the developer’s control. For example, if the app is in a group called “foo” on [gitlab.com](https://gitlab.com/), then the domain name could be io.gitlab.foo. It should not be based on someone’s domain name, (e.g. com.google.foo). Maven Central OSSRH provides [good guidance](https://central.sonatype.org/publish/requirements/coordinates/).

If the A. ID is changed in the future, the app will be re-published as a new app.
This is not good for users as their app won't update.
That's why I'm asking you to set the ID now, please.

**Comment by ljubitje** [comment]
Heya. I'm not sure why this was closed, please answer my previous message.
